Repository CloudSlang/cs-content, pull requests merged in 2020-06, with the labels that each got.

#1212 Oracle cloud list instances
  content/io/cloudslang/oracle/oci/compute/instances/list_instances.sl
  test/io/cloudslang/oracle/oci/compute/instances/test_list_instances.yaml
Labels: Development

#1220 Added configurationName input on powershell_script.sl
  content/io/cloudslang/base/powershell/powershell_script.sl
Labels: Development, kind/enhancement

#1222 Added Pwsh operation
  content/io/cloudslang/base/powershell/pwsh.sl
Labels: Development, kind/enhancement

#1223 Added sl files for detach disks and delete nic
  content/io/cloudslang/nutanix/prism/disks/detach_disks.sl
  content/io/cloudslang/nutanix/prism/nics/delete_nic.sl
  test/io/cloudslang/nutanix/prism/disks/test_detach_disks.yaml
  test/io/cloudslang/nutanix/prism/nics/test_delete_nic.yaml
Labels: Development

#1232 removed the extra properties from workflows.
  content/io/cloudslang/nutanix/prism/delete_nic_from_vm.sl
  content/io/cloudslang/nutanix/prism/deploy_vm.sl
  content/io/cloudslang/nutanix/prism/detach_disks_from_vm.sl
  content/io/cloudslang/nutanix/prism/power_off_vm.sl
  content/io/cloudslang/nutanix/prism/power_on_vm.sl
  content/io/cloudslang/nutanix/prism/undeploy_vm.sl
Labels: Development

#1235 Security fixes for ABBYY Cloud OCR
  content/io/cloudslang/abbyy/cloud/v1/process_image.sl
  content/io/cloudslang/abbyy/cloud/v1/process_text_field.sl
Labels: kind/bug

#1237 Added potential malicious char escape in abbyy
  content/io/cloudslang/abbyy/cloud/v1/process_image.sl
  content/io/cloudslang/abbyy/cloud/v1/process_text_field.sl
Labels: kind/bug, kind/enhancement

#1240 Escaped chars in abbyy with different strategy for xml
  content/io/cloudslang/abbyy/cloud/v1/process_image.sl
  content/io/cloudslang/abbyy/cloud/v1/process_text_field.sl
Labels: kind/bug

#1242 Updated the description and gav version
  content/io/cloudslang/hashicorp/terraform/DeployModuleV2.sl
  content/io/cloudslang/hashicorp/terraform/UndeployModuleV2.sl
  content/io/cloudslang/hashicorp/terraform/UpdateModuleV2.sl
  content/io/cloudslang/hashicorp/terraform/organizations/create_organization.sl
  content/io/cloudslang/hashicorp/terraform/organizations/delete_organization.sl
  content/io/cloudslang/hashicorp/terraform/organizations/get_organization_details.sl
  content/io/cloudslang/hashicorp/terraform/organizations/list_organizations.sl
  content/io/cloudslang/hashicorp/terraform/organizations/update_organization.sl
  content/io/cloudslang/hashicorp/terraform/runs/apply_run.sl
  content/io/cloudslang/hashicorp/terraform/runs/cancel_run.sl
  content/io/cloudslang/hashicorp/terraform/runs/create_run.sl
  content/io/cloudslang/hashicorp/terraform/runs/get_apply_details.sl
  content/io/cloudslang/hashicorp/terraform/runs/get_plan_details.sl
  content/io/cloudslang/hashicorp/terraform/runs/get_run_details.sl
  content/io/cloudslang/hashicorp/terraform/runs/list_runs_in_a_workspace.sl
  content/io/cloudslang/hashicorp/terraform/stateversions/get_current_state_version.sl
  content/io/cloudslang/hashicorp/terraform/utils/counter.sl
  content/io/cloudslang/hashicorp/terraform/utils/list_o_auth_client.sl
  content/io/cloudslang/hashicorp/terraform/variables/create_variable.sl
  content/io/cloudslang/hashicorp/terraform/variables/create_variables.sl
  content/io/cloudslang/hashicorp/terraform/variables/delete_variable.sl
  content/io/cloudslang/hashicorp/terraform/variables/list_variable.sl
  content/io/cloudslang/hashicorp/terraform/variables/update_variable.sl
  content/io/cloudslang/hashicorp/terraform/variables/update_variables.sl
  content/io/cloudslang/hashicorp/terraform/workspaces/create_workspace.sl
  content/io/cloudslang/hashicorp/terraform/workspaces/delete_workspace.sl
  content/io/cloudslang/hashicorp/terraform/workspaces/get_workspace_details.sl
  content/io/cloudslang/hashicorp/terraform/workspaces/list_workspaces.sl
  content/io/cloudslang/hashicorp/terraform/workspaces/variables/create_workspace_variable.sl
  content/io/cloudslang/hashicorp/terraform/workspaces/variables/create_workspace_variables.sl
  content/io/cloudslang/hashicorp/terraform/workspaces/variables/delete_workspace_variable.sl
  content/io/cloudslang/hashicorp/terraform/workspaces/variables/list_workspace_variable.sl
  content/io/cloudslang/hashicorp/terraform/workspaces/variables/update_workspace_variable.sl
  content/io/cloudslang/hashicorp/terraform/workspaces/variables/update_workspace_variables.sl
Labels: Development
